

# use an existing docker image as base
FROM alpine


# Download and install dependency
RUN apk add --update redis
RUN apk add --update gcc


#tell the image what to do when it
# starts a container

CMD ["redis-server"]
